algorithm: pet
save_dir: 
  ./saved_models/config/adaptformer/pet-ensembled-across-nets/resisc45/1-shot/clip
save_name: log
resume: true
load_path: 
  ./saved_models/config/adaptformer/pet-ensembled-across-nets/resisc45/1-shot/clip/log/latest_model.pth
overwrite: true
use_tensorboard: true
use_wandb: false
epoch: 30
num_train_iter: 23610
num_log_iter: 196
num_eval_iter: 1574
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 590
num_labels: 45
ema_m: 0.0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0001
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: false
clip: 0.0
use_cat: true
net: timm/vit_base_patch16_clip_224.openai
net_from_name: false
data_dir: ./data
dataset: resisc45
train_sampler: RandomSampler
num_classes: 45
num_workers: 4
seed: 0
world_size: 1
rank: 0
gpu: None
use_pretrain: true
# VTAB settings
train_split: train
eval_on_test: true
evaluate_unsupervised: false
es_patience: 0.0
# PET settings
w_alpha: 0.0
s_alpha: 0.0
kd_w_alpha: 1.0
kd_s_alpha: 1.0
temperature: 1.0
budget: 1.0
pet_sources:
- "config/lora/supervised/resisc45/1-shot/dinov2/dpr-0/train-aug-strong/{'lora_bottleneck':
  16}/lr-1e-3/config.yaml"
- "config/lora/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck':
  16}/lr-1e-3/config.yaml"
- "config/adaptformer/supervised/resisc45/1-shot/dinov2/dpr-0.2/train-aug-strong/{'adapter_scaler':
  0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
- "config/adaptformer/supervised/resisc45/1-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler':
  0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
pl_selection: balanced-max
logits_ensemble: voting
bootstrapping: true
peft_config:
  method_name: adaptformer
  ft_mlp_module: adapter
  ft_mlp_mode: parallel
  ft_mlp_ln: before
  adapter_init: lora_kaiming
  adapter_bottleneck: 16
  adapter_scaler: 0.1
vit_config:
  drop_path_rate: 0.0
pet_sources_rows:
- - lora
  - supervised
  - resisc45
  - 1-shot
  - dinov2
  - "['dpr-0', 'train-aug-strong', \"{'lora_bottleneck': 16}\", 'lr-1e-3']"
  - 539.4315795898438
  - 0.620851272765391
  - 0.36535036817197936
  - 0.6427364825118086
  - 0.3826364412317556
  - 80.57756805419922
  - 0.06093626469373703
  - 0.49269840121269226
  - '2025-12-30 18:02:34'
- - lora
  - supervised
  - resisc45
  - 1-shot
  - clip
  - "['dpr-0', 'train-aug-strong', \"{'lora_bottleneck': 16}\", 'lr-1e-3']"
  - 442.122314453125
  - 0.6970380511193951
  - 0.47852863971450355
  - 0.7144132315909228
  - 0.49334074121982097
  - 112.38765716552734
  - 0.059080105274915695
  - 0.5842857360839844
  - '2025-12-30 18:02:34'
- - adaptformer
  - supervised
  - resisc45
  - 1-shot
  - dinov2
  - "['dpr-0.2', 'train-aug-strong', \"{'adapter_scaler': 0.1, 'adapter_bottleneck':
    4}\", 'lr-1e-3']"
  - 494.484375
  - 0.4977454966043752
  - 0.22802264085286822
  - 0.5256427759715784
  - 0.2562706998986079
  - 92.87066650390625
  - 0.03329974412918091
  - 0.3698412775993347
  - '2025-12-30 18:02:35'
- - adaptformer
  - supervised
  - resisc45
  - 1-shot
  - clip
  - "['dpr-0', 'train-aug-strong', \"{'adapter_scaler': 0.1, 'adapter_bottleneck':
    16}\", 'lr-1e-3']"
  - 417.3996887207031
  - 0.710784983974793
  - 0.5139675041976247
  - 0.7272850957282029
  - 0.5260873014305153
  - 114.57291412353516
  - 0.058062199503183365
  - 0.6082539558410645
  - '2025-12-30 18:02:35'
