algorithm: pet
save_dir: 
  ./saved_models/config/adaptformer/pet-ensembled-across-nets/dtd/16-shot/dinov2
save_name: log
resume: true
load_path: 
  ./saved_models/config/adaptformer/pet-ensembled-across-nets/dtd/16-shot/dinov2/log/latest_model.pth
overwrite: true
use_tensorboard: true
use_wandb: false
epoch: 30
num_train_iter: 3270
num_log_iter: 27
num_eval_iter: 218
batch_size: 8
eval_batch_size: 16
num_warmup_iter: 81
num_labels: 752
ema_m: 0.0
img_size: 224
crop_ratio: 0.875
optim: AdamW
lr: 0.0001
layer_decay: 1.0
momentum: 0.9
weight_decay: 0.0005
amp: false
clip: 0.0
use_cat: true
net: timm/vit_base_patch14_reg4_dinov2.lvd142m
net_from_name: false
data_dir: ./data
dataset: dtd
train_sampler: RandomSampler
num_classes: 47
num_workers: 4
seed: 0
world_size: 1
rank: 0
gpu: None
use_pretrain: true
# VTAB settings
train_split: train
eval_on_test: true
evaluate_unsupervised: false
es_patience: 0.0
# PET settings
w_alpha: 0.0
s_alpha: 0.0
kd_w_alpha: 1.0
kd_s_alpha: 1.0
temperature: 1.0
budget: 1.0
pet_sources:
- "config/adaptformer/supervised/dtd/16-shot/clip/dpr-0/train-aug-strong/{'adapter_scaler':
  0.1, 'adapter_bottleneck': 16}/lr-1e-3/config.yaml"
- "config/adaptformer/supervised/dtd/16-shot/dinov2/dpr-0.2/train-aug-strong/{'adapter_scaler':
  0.1, 'adapter_bottleneck': 4}/lr-1e-3/config.yaml"
- "config/lora/supervised/dtd/16-shot/clip/dpr-0/train-aug-strong/{'lora_bottleneck':
  16}/lr-1e-3/config.yaml"
- "config/lora/supervised/dtd/16-shot/dinov2/dpr-0/train-aug-strong/{'lora_bottleneck':
  16}/lr-1e-3/config.yaml"
pl_selection: balanced-max
logits_ensemble: voting
bootstrapping: true
peft_config:
  method_name: adaptformer
  ft_mlp_module: adapter
  ft_mlp_mode: parallel
  ft_mlp_ln: before
  adapter_init: lora_kaiming
  adapter_bottleneck: 16
  adapter_scaler: 0.1
vit_config:
  drop_path_rate: 0.0
pet_sources_rows:
- - adaptformer
  - supervised
  - dtd
  - 16-shot
  - clip
  - "['dpr-0', 'train-aug-strong', \"{'adapter_scaler': 0.1, 'adapter_bottleneck':
    16}\", 'lr-1e-3']"
  - 389.2135009765625
  - 0.663633032725562
  - 0.46991396499348476
  - 0.769643081800634
  - 0.4834046619957559
  - 12.973099188201093
  - 0.19747202098369598
  - 0.7372340559959412
  - '2026-01-22 21:40:58'
- - adaptformer
  - supervised
  - dtd
  - 16-shot
  - dinov2
  - "['dpr-0.2', 'train-aug-strong', \"{'adapter_scaler': 0.1, 'adapter_bottleneck':
    4}\", 'lr-1e-3']"
  - 407.6917724609375
  - 0.6656925251038702
  - 0.49743596865031675
  - 0.7709857888204298
  - 0.5096892070028548
  - 13.26712601638225
  - 0.2040206491947174
  - 0.7393617033958435
  - '2026-01-22 21:40:58'
- - lora
  - supervised
  - dtd
  - 16-shot
  - clip
  - "['dpr-0', 'train-aug-strong', \"{'lora_bottleneck': 16}\", 'lr-1e-3']"
  - 380.6116638183594
  - 0.7328642611560693
  - 0.587876913378169
  - 0.817465753885575
  - 0.5973336168633875
  - 16.28291438564711
  - 0.2072739154100418
  - 0.7367021441459656
  - '2026-01-22 21:40:58'
- - lora
  - supervised
  - dtd
  - 16-shot
  - dinov2
  - "['dpr-0', 'train-aug-strong', \"{'lora_bottleneck': 16}\", 'lr-1e-3']"
  - 450.2820739746094
  - 0.6700695049068219
  - 0.5013581220783854
  - 0.7741395184515609
  - 0.5138366099961388
  - 11.43656536387265
  - 0.2143435776233673
  - 0.7792553305625916
  - '2026-01-22 21:40:58'
